"""
make_fig4.py - Fig. 4 and the metric-trap table.

The Sun-Earth-Moon result: a fixed-step leapfrog run at dt = 0.01 conserves
global energy to 0.007867 percent and passes the global bounded check, while
the Earth to Moon separation runs out to 1.98950 AU, about 774 times the true
0.00257 AU. The Moon is gone and the global metrics do not notice. That is why
the paper's diagnostic panel carries a pair-separation range alongside energy
and boundedness.

WHICH RUNS ARE PLOTTED, AND WHY. The five series here are the five the paper's
Results section names: IAS15, TSALF, and fixed-step leapfrog at dt = 0.04,
0.01 and 0.005. The figure in v1.9 and v1.10 instead plotted dt = 0.02, which
the text never discusses for this system, and left out dt = 0.005, which the
text names explicitly as preserving the lunar separation. No dt = 0.02
Sun-Earth-Moon run exists in this repository or in the wider research tree, so
that trace could not be regenerated by anyone. Swapping it for dt = 0.005
makes the figure match the text and makes every trace reproducible from
outputs/sun_earth_moon_run.json.

The heuristic adaptive run is not plotted and is no longer in the table. The
paper compares three integrators and never discusses it.

Reads the frozen Sun-Earth-Moon run in outputs/sun_earth_moon_run.json rather
than recomputing it, because regenerating it means refetching live state
vectors from JPL Horizons. See the description field in that file.

Drawn to the CJSJ template's figure specification: single column width, 8 point
Times New Roman, axis labels in words rather than symbols or abbreviations,
units in parentheses, no chart title, 300 dpi. The key sits below the axes, as
it does in the manuscript's own version: at one column width anything placed
inside covers either the unbound runs or the bound ones, and the bound ones
holding at the true lunar separation are what the panel is read for.

Run:  python scripts/make_fig4.py
Out:  outputs/metric_trap_table.txt, figures/fig4_earth_moon_separation.png
"""
import json, os
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "outputs")
FIGS = os.path.join(ROOT, "figures")
os.makedirs(OUT, exist_ok=True); os.makedirs(FIGS, exist_ok=True)

d = json.load(open(os.path.join(OUT, "sun_earth_moon_run.json")))
res = d["results"]; ss = d["sem_series"]
sem = {r["method"]: r for r in res if r["config"] == "SEM"}  # SEM = the sweep's label for the Sun-Earth-Moon configuration
TRUE_EM = 0.00257  # mean Earth-Moon distance, AU

LABEL = {"ias15": "IAS15 (reference)", "tsalf": "TSALF",
         "leapfrog_0.005": "Leapfrog, step 0.005",
         "leapfrog_0.01": "Leapfrog, step 0.01",
         "leapfrog_0.04": "Leapfrog, step 0.04"}
order = ["ias15", "tsalf", "leapfrog_0.005", "leapfrog_0.01", "leapfrog_0.04"]
COLOUR = {"ias15": "#111111", "tsalf": "#1f77b4", "leapfrog_0.005": "#9467bd",
          "leapfrog_0.01": "#d62728", "leapfrog_0.04": "#ff7f0e"}

# ---------------------------- the metric-trap table ----------------------------
L = ["METRIC-TRAP RESULT - real Sun-Earth-Moon (JPL Horizons ICs), Newtonian point masses, T=100 yr",
     "Global energy verdict vs pair-separation truth. True Earth-Moon distance ~ %.5f AU." % TRUE_EM,
     "=" * 100,
     f"{'method':18} {'max|dE/E0|':>12} {'bounded':>8} {'EM-sep range [AU]':>26} {'peak/true':>10}  verdict"]
disp = {"ias15": "ias15 (ref)", "tsalf": "tsalf",
        "leapfrog_0.005": "leapfrog dt=0.005", "leapfrog_0.01": "leapfrog dt=0.01",
        "leapfrog_0.04": "leapfrog dt=0.04"}
for m in order:
    r = sem[m]; pr = r["pair_range"]; peak = pr[1]; ratio = peak / TRUE_EM
    verdict = "PHYSICAL" if peak < 0.01 else "LUNAR ORBIT UNBOUND"
    L.append(f"{disp[m]:18} {r['max_dE_pct']:>11.4g}% {('yes' if r['bounded'] else 'no'):>8} "
             f"[{pr[0]:.5f}, {pr[1]:.5f}] {ratio:>9.0f}x  {verdict}")
L += ["=" * 100,
      "THE TRAP: leapfrog dt=0.01 reports max|dE/E0|=%.4g%% and bounded=True (global metric: 'fine')," % sem['leapfrog_0.01']['max_dE_pct'],
      "  yet the Earth-Moon separation runs out to %.2f AU = %.0fx the true %.5f AU (the Moon is ejected from Earth)." % (
          sem['leapfrog_0.01']['pair_range'][1], sem['leapfrog_0.01']['pair_range'][1] / TRUE_EM, TRUE_EM),
      "  ias15, tsalf and the finer fixed step dt=0.005 keep it physical at ~[0.0024, 0.0030] AU.",
      "  => A global energy/boundedness check certifies a run whose internal hierarchical structure is destroyed.",
      "     A pair-separation metric is REQUIRED to catch this; it is the headline 'metric trap'."]
open(os.path.join(OUT, "metric_trap_table.txt"), "w").write("\n".join(L) + "\n")
print("\n".join(L)); print()

# ---------------------------------- Fig. 4 ------------------------------------
# CJSJ template figure specification
plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Liberation Serif", "Nimbus Roman", "DejaVu Serif"],
    "font.size": 8, "axes.linewidth": 0.8,
    "xtick.labelsize": 8, "ytick.labelsize": 8,
    "legend.fontsize": 7, "axes.labelsize": 8,
})
COLUMN_IN = 3.4                      # CJSJ two-column text block, one column
fig, ax = plt.subplots(figsize=(COLUMN_IN, COLUMN_IN * 1.06))
for m in order:
    ax.plot(ss[m]["t"], ss[m]["em"], label=LABEL[m], color=COLOUR[m], lw=0.9)
ax.axhline(TRUE_EM, color="green", ls=":", lw=1.1,
           label=f"True lunar distance {TRUE_EM:.5f} AU")
ax.set_yscale("log")
ax.set_xlabel("Time (years)", labelpad=3)
ax.set_ylabel("Earth to Moon separation (AU)", labelpad=3)
ax.grid(alpha=0.25, which="both", lw=0.4)
# key below the axes: see the module docstring
ax.legend(fontsize=6.2, loc="upper center", bbox_to_anchor=(0.5, -0.20), ncol=2,
          framealpha=0.95, edgecolor="0.7", handlelength=1.8, labelspacing=0.3,
          columnspacing=1.2, borderpad=0.4)
fig.tight_layout()
dest = os.path.join(FIGS, "fig4_earth_moon_separation.png")
fig.savefig(dest, dpi=300, bbox_inches="tight")
print(f"wrote {os.path.join(OUT,'metric_trap_table.txt')}")
print(f"wrote {dest}")
print(f"  series plotted: {', '.join(order)}")
